app = "nos-tlplot"
primary_region = "bom"

[build]
  builder = "paketobuildpacks/builder:full"
  [build.env]
    BP_PYTHON_VERSION = "3.11.*"
    PIP_NO_CACHE_DIR = "true"   # forces fresh wheel builds to avoid numpy import errors

[processes]
  app = "streamlit run app.py --server.port=8501 --server.address=0.0.0.0 --server.headless=true"

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
